

steps:
## Build the image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/test-server-359505/cloud-run-source-deploy/xmv-server-image:latest', '.']
## Push the image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/test-server-359505/cloud-run-source-deploy/xmv-server-image:latest']
## Deploy image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'deploy-to-cloud-run' 
  entrypoint: gcloud
  args: ['run', 'deploy', 'test-server', '--image', 'us-central1-docker.pkg.dev/test-server-359505/cloud-run-source-deploy/xmv-server-image:latest', '--region', 'us-central1'
    , '--platform', 'managed', '--port=8080', '--allow-unauthenticated']
images:
- 'us-central1-docker.pkg.dev/test-server-359505/cloud-run-source-deploy/xmv-server-image:latest'
options:
  logging: CLOUD_LOGGING_ONLY

##### gcloud builds submit --region=us-central1