steps:
# Build the image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/test-server-359505/cloud-run-source-deploy/xmv-server', '.']
# Push the image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev//cloud-run-source-deploy/xmv-server']
# Deploy image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'test-server', '--image', 'us-central1-docker.pkg.dev/test-server-359505/cloud-run-source-deploy/xmv-server', '--region', 'us-central1']
images:
- 'us-central1-docker.pkg.dev/test-server/cloud-run-source-deploy/xmv-server'